### ISSUE TITLE
Daily forecast from EC offset by 1 day

### ISSUE THREAD

**Issue by lfroms** [lfroms/nimbus#23]
**Describe the bug**
In rare occasions, the data returned from the MSC Datamart for the daily forecast is mislabelled, resulting in the forecasts being offset by 1 day.

Code in question: [`daily_factory.rb`](https://github.com/lfroms/nimbus/blob/master/app/services/weather/environment_canada/factories/daily_factory.rb#L41).

**To Reproduce**
Only occurs in rare circumstances when the data is not formatted as expected.

**Expected behavior**
Regardless of input data, the forecast is correctly produced.

**Additional context**
Originally spotted by @williamlauzon in lfroms/clouds#72.

**Comment by williamlauzon** [comment]
Just a heads up, I noticed this issue happening last night (February 11th) and tonight (February 12th). The forecast displayed is correct, but the dates displayed are incorrect. For example, today's weather and tomorrow's weather appear to match what is on the EC website, but today is labelled as February 13th and tomorrow is labelled as February 14th. Also, in case it helps to provide additional context, another app using the EC data (but not WeatherCAN) is correctly displaying the dates right now. I just thought I would provide some details in case it helps identify this issue better!

**Comment by lfroms** [comment]
Thanks, @williamlauzon. I've confirmed that this is a parsing issue in Nimbus. The code made certain assumptions about the data that did not always hold true.

I'll be deploying a fix shortly.

**Comment by lfroms** [comment]
Reopening temporarily as there appears to be a bug in the code where the dates are incorrect on certain days of the week.
